version = 0.1
[default.deploy.parameters]
stack_name = "java-spring-movies-api"
resolve_s3 = true
s3_prefix = "java-spring-movies-api"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
