package dev.bilal.movies.movie;


import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;


@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "movies")
public class Movie {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String movieId;

    @DynamoDBAttribute
    private String imdbId;

    @DynamoDBAttribute
    private String title;

    @DynamoDBAttribute
    private String releaseDate;

    @DynamoDBAttribute
    private String trailerLink;

    @DynamoDBAttribute
    private String poster;

    @DynamoDBAttribute
    private List<String> genres;

    @DynamoDBAttribute
    private List<String> backdrops;

    @DynamoDBAttribute
    private List<String> reviewIds;

    public Movie(String imdbId, String title, String releaseDate, String trailerLink, String poster, List<String> genres, List<String> backdrops, List<String> reviewIds) {
        this.imdbId = imdbId;
        this.title = title;
        this.releaseDate = releaseDate;
        this.trailerLink = trailerLink;
        this.poster = poster;
        this.genres = genres;
        this.backdrops = backdrops;
        this.reviewIds = reviewIds;
    }
}
