package dev.bilal.movies.review;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;


@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "reviews")
public class Review {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String reviewId;

    @DynamoDBAttribute
    private String body;

    public Review(String body) {
        this.body = body;
    }
}
